sonar.projectKey=nmedia-AmmarAhmad_2-tier-devops-project
sonar.organization=nmedia-ammarahmad  # <--- Replace this with your actual Org Key!
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,test/**