sonar.projectKey=ammar-2tier-pro
sonar.projectName=Ammar 2-Tier Pro
sonar.projectVersion=1.0
# Tell it where the code and tests are
sonar.sources=.
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Don't scan the node_modules folder (it's too big!)
sonar.exclusions=node_modules/**