name: Ammar-Pro-CI-CD

on:
  push:
    branches: [ main ]

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install Dependencies
        run: npm install
      - name: Run Tests & Coverage
        run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Note: The 'deploy' job is removed here because the 
  # Auto Scaling Group in your asg.tf will now handle 
  # pulling the code automatically on boot-up.